#!/bin/bash

# The USB drive MUST be labeled as "XBT_Drive" for the script to run.

if [ ! -d /media/"$USER"/XBT_Drive ]; then
	echo "NO DRIVE FOUND! Please make sure XBT_Drive USB is connected." ; exit 1
fi

clear
echo "
XBT -- External Backup Tool (Version 1.7 - Ilan Shavit)
"
# Log file is created in /tmp:

echo "Backup sent to XBT_Drive USB from $HOSTNAME by '$USER' on:" \
> /tmp/backup.log
date >> /tmp/backup.log
echo "Errors:" >> /tmp/backup.log

# Begin backup operations using rsync:
# (User will be prompted for sudo password if XBT was not started with sudo.)

# Creating machine specific directories:

mkdir -p /media/"$USER"/XBT_Drive/XBT_Backups/"$HOSTNAME"

# Starting synchronization:

echo "
Backing up /home..."
rsync -aq --delete --exclude '/home/"$USER"/.cache'  /home/"$USER"/ /media/"$USER"/XBT_Drive/XBT_Backups/"$HOSTNAME"/home/  2>> /tmp/backup.log
echo "--------------------
-  All backed up!  -
--------------------" | tee -a /tmp/backup.log

# Log file is created or appended on XBT_Drive from /tmp:
# (backup.log will be removed from /tmp on next reboot.)

cat /tmp/backup.log >> /media/"$USER"/XBT_Drive/XBT_Backups/xbt-backup.log

# Writing all cached data to drives and exiting:

echo "Wait! Syncing drives..."
sync
echo "...Done.
It's now safe to remove XBT_Drive. Thanks for using XBT!
"
exit

