#!/bin/sh
# Version: 1.02
# Developer: ilan.shavit@gmail.com
ts=$(date  +%Y%m%d-%H%M%S)
if [ $# = 2 ] ; then
    if [ "$1" = -c ] ; then
       cp -p "$2" "$2_$ts"
    elif [ "$1" = -m ] ; then
       mv "$2" "$2_$ts"
    else
       echo "Usage: ts -c filename"
       echo "       ts -m filename"
    fi
else
    echo "Usage: ts -c filename"
    echo "       ts -m filename"
fi
